name: Create Newsletter Tracking Issue
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:
    inputs: {}
environment:
  name: newsletter
permissions:
  contents: read
  issues: write 
jobs:
  create-newsletter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set date
        run: echo "NEWSLETTER_DATE=$(date)" >> $GITHUB_ENV
      - name: Create tracking issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/newsletter-template.md

