name: Create Newsletter Tracking Issue
on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read
  issues: write 
jobs:
  create-newsletter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "TODO=$(date)" >> $GITHUB_ENV
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/newsletter-template.md

