name: Create Newsletter
on:
  schedule:
    # Run on the 5th of every month at 12pm
    - cron: "0 12 5 * *"
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
  issues: write 
jobs:
  create-newsletter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          echo "NEWSLETTER_MONTH=$(date +'%B')" >> $GITHUB_ENV
          echo "NEWSLETTER_YEAR=$(date +'%Y')" >> $GITHUB_ENV
          echo "NEWSLETTER_DEADLINE=$(date -d' 1 month ' '+%m.%Y')" >> $GITHUB_ENV
          # take the amount of months since feb 2024 and add 50
          echo "NEWSLETTER_COUNTER=$(( ( ( $(date +'%Y') - 2024 ) * 12 + $(date +'%m') - 2 ) + 50 ))" >> $GITHUB_ENV
      - name: Create newsletter scaffold
        uses: edgardleal/mustache-template-action@v1.0.0    
        env:
          ENV: dev
        with:
          input: newsletter-template.md
          output: newsletter.md
      - name: Create tracking issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/newsletter-template.md

